# Generated by Django 3.1.13 on 2021-08-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200)),
                ('rasm', models.ImageField(upload_to='rasmlar/playlist_rasm')),
                ('sana', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
